auth_url = https://auth.smallcase.com
smallcaseapi_url = https://api.smallcase.com
gatewayapi_url = https://gatewayapi.smallcase.com
otp_url =https://otp.smallcase.com
client_id =sc-platform-frontend
phoneCountryCode =+91
nexum-api=https://api.nexum.smallcase.com
provider =smallcase
Internal_url =https://otp.prod.smallcase.com
internalClientId=backend-qa
internalphoneCountryCode=+SC
Email_client_id=sc-platform-email-login
search_url=https://api.smallcase.com
broker_url = https://scb.prod.smallcase.com


# BELOW configs are for OTP service automation. Keeping them separate from smallcase API, might move to a separate file altogether.
otp_service_url=https://otp.prod.smallcase.com
# name of the OTP service client to  be used in automation
otp_service_qa_client=be-qa-automation

# admin creds for OTP service for working with testUsers
otp_service_admin_client_id=backend-qa

# JWE Encryption Public Key (base64 encoded RSA public key)
# TODO: Add JWE Encryption Public Key in GitHub secrets
jwe_encryption_public_key = jwe_encryption_public_key_prod