auth_url = https://auth-stag.smallcase.com
smallcaseapi_url = https://api-stag.smallcase.com
gatewayapi_url = https://gatewayapi-stag.smallcase.com
otp_url = https://otp-stag.smallcase.com
client_id = smallcase-platform
phoneCountryCode = +91
nexum-api = https://api-stag.nexum.smallcase.com
provider = smallcase
Internal_url = https://otp.stag.smallcase.com
internalClientId = backend-qa
internalphoneCountryCode = +SC
Email_client_id = email-login
search_url= https://search.stag.smallcase.com
smallboard_url = https://smallboard-be.stag.smallcase.com
broker_url = https://scb.stag.smallcase.com


# BELOW configs are for OTP service automation. Keeping them separate from smallcase API, might move to a separate file altogether.
otp_service_url = https://otp-stag.smallcase.com
# name of the OTP service client to  be used in automation
otp_service_qa_client = be-qa-automation

# admin creds for OTP service for working with testUsers
otp_service_admin_client_id = backend-qa

# JWE Encryption Public Key (base64 encoded RSA public key)
jwe_encryption_public_key = jwe_encryption_public_key_stage
#---------------------------------------------------------------------------------------------------------------