auth_url = https://auth-dev.smallcase.com
smallcaseapi_url = https://api-dev.smallcase.com

# JWE Encryption Public Key (base64 encoded RSA public key)
# TODO: Add JWE Encryption Public Key in GitHub secrets
jwe_encryption_public_key = jwe_encryption_public_key_dev